const assert=require('node:assert/strict');
const beasts=require('../beast-rules.js').BaziBeasts;
const game=require('../life-game.js').BaziLifeGame;
const chart={counts:{木:3,火:3,土:1,金:1,水:2},gods:{比劫:2,食傷:3,財星:1,官殺:2,印星:2},strength:'身偏強'};
const reading={beastMatch:beasts.classify(chart),capabilities:beasts.capabilities(chart)};
assert.equal(beasts.profiles.length,8);
assert.equal(new Set(beasts.profiles.map(p=>p.id)).size,8);
assert.notEqual(beasts.classify({...chart,gods:{比劫:8,食傷:0,財星:0,官殺:0,印星:0}}).primary.profile.id,beasts.classify({...chart,gods:{比劫:0,食傷:0,財星:0,官殺:0,印星:8}}).primary.profile.id);
assert.equal(game.stages.length,8);
assert.ok(game.stages.every(stage=>stage.cards.length===2));
assert.equal(new Set(game.stages.flatMap(stage=>stage.cards.map(card=>card.title))).size,16);
function play(choice){const state=game.create(reading);assert.equal(state.phase,'choose');for(let i=0;i<8;i++){assert.equal(state.phase,'choose');const result=game.choose(state,choice);assert.equal(result.round,i+1);assert.ok(Object.values(state.stats).every(n=>n>=0&&n<=100));game.next(state)}assert.equal(state.phase,'done');return game.summary(state)}
const low=play(0),high=play(1);
assert.equal(low.breakout,false);
assert.equal(high.breakout,true);
assert.equal(low.history.length,8);
const exact=game.create(reading);exact.phase='done';exact.stats={energy:80,relations:80,wealth:80,achievement:80};
assert.equal(game.summary(exact).breakout,false);
exact.stats.achievement=84;
assert.equal(game.summary(exact).breakout,true);
console.log('Eight beasts, sixteen scenes, eight rounds and strict >80 breakout: OK');
